version: v1.1
# 向量数据库
vector_store:
#  provider: pgvector
#  config:
#    host: postgres
#    port: 5432
#    dbname: postgres
#    user: postgres
#    password: postgres
#    collection_name: memories
#    embedding_model_dims: 1024
  provider: qdrant
  config:
    embedding_model_dims: 1024
    collection_name: mem0
    host: 192.168.10.4
    port: 6333

# 图数据库
#graph_store:
#  provider: neo4j
#  config:
#    url: bolt://192.168.10.4:7687
#    username: neo4j
#    password: mem0graph
#  llm:
#    provider: openai
#    config:
#      openai_base_url: https://dashscope.aliyuncs.com/compatible-mode/v1
#      api_key: sk-d6fe04d87ad14c20b4955da27944aaff
#      model: qwen2.5-72b-instruct
#      temperature: 0.1

# 大模型
llm:
#  provider: ollama
#  config:
#    ollama_base_url: http://192.168.0.10:11434
#    model: qwen2.5:7b
#    temperature: 0.1
#    max_tokens: 2000
  provider: openai
  config:
#    openai_base_url: https://api.siliconflow.cn/v1
#    api_key: sk-nucpbxyydswpwjsgkclqsdtejatbhhkrxiqayvfiizfjuhyo
#    model: Qwen/Qwen2.5-7B-Instruct
    openai_base_url: https://dashscope.aliyuncs.com/compatible-mode/v1
    api_key: sk-7350457c960d42b1a837fd079d9422d8
    model: qwen2.5-72b-instruct
    temperature: 0.1
#    max_tokens: 2000

embedder:
#  provider: ollama
#  config:
#    ollama_base_url: http://192.168.0.10:11434
#    model: mxbai-embed-large:335m
  provider: openai
  config:
    # ollama_base_url: http://192.168.10.4:11434
    openai_base_url: https://api.siliconflow.cn/v1
    api_key: sk-nucpbxyydswpwjsgkclqsdtejatbhhkrxiqayvfiizfjuhyo
    model: BAAI/bge-m3
    # model: mxbai-embed-large:335m

history_db_path: ./history.db